=== hhortelano/hhortelanolm/LENGUAJES/TEMA6/ejercicioExamen3/peliculas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pelicula">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="actor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre"></xs:element>
                                        <xs:element name="apellidos"></xs:element>
                                        <xs:element name="edad"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="codigo" type="xs:ID"/> 
                                    <xs:attribute name="rol" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="director"></xs:element>
                <xs:element name="anio"></xs:element>
                <xs:element name="duracion"></xs:element>
                <xs:element name="sinopsis"></xs:element>
                <xs:element name="generos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="genero" maxOccurs="unbounded" minOccurs="0"></xs:element>
                        </xs:sequence>
                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
            <xs:attribute name="titulo" type="xs:string"/>
            <xs:attribute name="clasificacion" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hhortelano/hhortelanolm/LENGUAJES/TEMA6/ejercicioExamen3/peliculas.xml
<?xml version="1.0" encoding="UTF-8"?>

<pelicula id="ABC1234" titulo="Madagascar" clasificacion="ATP" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="peliculas.xsd">
    <actores>
        <actor codigo="A1" rol="protagonista">
            <nombre></nombre>
            <apellidos></apellidos>
            <edad></edad>
        </actor>
        <actor codigo="A2" rol="extra">
            <nombre></nombre>
            <apellidos></apellidos>
            <edad></edad>
        </actor>
    </actores>
    <director></director>
    <anio></anio>
    <duracion></duracion>
    <sinopsis></sinopsis>
    <generos>
        <genero nombre="Accion"></genero>
        <genero nombre="Ciencia Ficcion"></genero>
    </generos>
</pelicula>
